# https://docs.travis-ci.com/user/languages/ruby
language: ruby
cache: bundler
rvm:
  - 2.4.0
script:
  - bundle exec rspec
  
# https://docs.travis-ci.com/user/notifications
notifications:
  email: false
